<?php

/**
 * @file
 * Contains tax_by_vocabulary.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function tax_by_vocabulary_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tax_by_vocabulary module.
    case 'help.page.tax_by_vocabulary':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tax_by_vocabulary_theme($existing, $type, $theme, $path) {

  return [
      'taxbyvocabulary' => [
          'variables' => [
              'name' => '',
              'attributes' => [],
              'count_items' => 0,
              'items' => [],
          ],
      ],
  ];

}

/**
 * Implements hook_theme_suggestions_taxbyvocabulary().
 */
function tax_by_vocabulary_theme_suggestions_taxbyvocabulary($variables) {
  return 'taxbyvocabulary__' . Html::cleanCssIdentifier($variables['name']);
}
